/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CategoriesRouteImport } from './routes/categories'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as SearchRouteImport } from './routes/search'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AppsIndexRouteImport } from './routes/apps/index'
import { Route as AppsAgriBizRouteImport } from './routes/apps/agri-biz'
import { Route as AppsAnimalClinicRouteImport } from './routes/apps/animal-clinic'
import { Route as AppsEducationRouteImport } from './routes/apps/education'
import { Route as AppsPlantClinicRouteImport } from './routes/apps/plant-clinic'
import { Route as CategoriesSlugRouteImport } from './routes/categories.$slug'
import { Route as ProfileIdRouteImport } from './routes/profile.$id'
import { Route as ProjectsIdRouteImport } from './routes/projects.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesRoute = CategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppsIndexRoute = AppsIndexRouteImport.update({
  id: '/apps/',
  path: '/apps/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppsAgriBizRoute = AppsAgriBizRouteImport.update({
  id: '/apps/agri-biz',
  path: '/apps/agri-biz',
  getParentRoute: () => rootRouteImport,
} as any)
const AppsAnimalClinicRoute = AppsAnimalClinicRouteImport.update({
  id: '/apps/animal-clinic',
  path: '/apps/animal-clinic',
  getParentRoute: () => rootRouteImport,
} as any)
const AppsEducationRoute = AppsEducationRouteImport.update({
  id: '/apps/education',
  path: '/apps/education',
  getParentRoute: () => rootRouteImport,
} as any)
const AppsPlantClinicRoute = AppsPlantClinicRouteImport.update({
  id: '/apps/plant-clinic',
  path: '/apps/plant-clinic',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesSlugRoute = CategoriesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => CategoriesRoute,
} as any)
const ProfileIdRoute = ProfileIdRouteImport.update({
  id: '/profile/$id',
  path: '/profile/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIdRoute = ProjectsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ProjectsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/categories': typeof CategoriesRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/onboarding': typeof OnboardingRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/search': typeof SearchRoute
  '/apps/agri-biz': typeof AppsAgriBizRoute
  '/apps/animal-clinic': typeof AppsAnimalClinicRoute
  '/apps/education': typeof AppsEducationRoute
  '/apps/plant-clinic': typeof AppsPlantClinicRoute
  '/categories/$slug': typeof CategoriesSlugRoute
  '/profile/$id': typeof ProfileIdRoute
  '/projects/$id': typeof ProjectsIdRoute
  '/admin/': typeof AdminIndexRoute
  '/apps/': typeof AppsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/categories': typeof CategoriesRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/onboarding': typeof OnboardingRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/search': typeof SearchRoute
  '/apps/agri-biz': typeof AppsAgriBizRoute
  '/apps/animal-clinic': typeof AppsAnimalClinicRoute
  '/apps/education': typeof AppsEducationRoute
  '/apps/plant-clinic': typeof AppsPlantClinicRoute
  '/categories/$slug': typeof CategoriesSlugRoute
  '/profile/$id': typeof ProfileIdRoute
  '/projects/$id': typeof ProjectsIdRoute
  '/admin': typeof AdminIndexRoute
  '/apps': typeof AppsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/categories': typeof CategoriesRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/onboarding': typeof OnboardingRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/search': typeof SearchRoute
  '/apps/agri-biz': typeof AppsAgriBizRoute
  '/apps/animal-clinic': typeof AppsAnimalClinicRoute
  '/apps/education': typeof AppsEducationRoute
  '/apps/plant-clinic': typeof AppsPlantClinicRoute
  '/categories/$slug': typeof CategoriesSlugRoute
  '/profile/$id': typeof ProfileIdRoute
  '/projects/$id': typeof ProjectsIdRoute
  '/admin/': typeof AdminIndexRoute
  '/apps/': typeof AppsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/categories'
    | '/dashboard'
    | '/onboarding'
    | '/projects'
    | '/search'
    | '/apps/agri-biz'
    | '/apps/animal-clinic'
    | '/apps/education'
    | '/apps/plant-clinic'
    | '/categories/$slug'
    | '/profile/$id'
    | '/projects/$id'
    | '/admin/'
    | '/apps/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/categories'
    | '/dashboard'
    | '/onboarding'
    | '/projects'
    | '/search'
    | '/apps/agri-biz'
    | '/apps/animal-clinic'
    | '/apps/education'
    | '/apps/plant-clinic'
    | '/categories/$slug'
    | '/profile/$id'
    | '/projects/$id'
    | '/admin'
    | '/apps'
  id:
    | '__root__'
    | '/'
    | '/categories'
    | '/dashboard'
    | '/onboarding'
    | '/projects'
    | '/search'
    | '/apps/agri-biz'
    | '/apps/animal-clinic'
    | '/apps/education'
    | '/apps/plant-clinic'
    | '/categories/$slug'
    | '/profile/$id'
    | '/projects/$id'
    | '/admin/'
    | '/apps/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CategoriesRoute: typeof CategoriesRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  OnboardingRoute: typeof OnboardingRoute
  ProjectsRoute: typeof ProjectsRouteWithChildren
  SearchRoute: typeof SearchRoute
  AppsAgriBizRoute: typeof AppsAgriBizRoute
  AppsAnimalClinicRoute: typeof AppsAnimalClinicRoute
  AppsEducationRoute: typeof AppsEducationRoute
  AppsPlantClinicRoute: typeof AppsPlantClinicRoute
  ProfileIdRoute: typeof ProfileIdRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AppsIndexRoute: typeof AppsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories': {
      id: '/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof CategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apps/': {
      id: '/apps/'
      path: '/apps'
      fullPath: '/apps/'
      preLoaderRoute: typeof AppsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apps/agri-biz': {
      id: '/apps/agri-biz'
      path: '/apps/agri-biz'
      fullPath: '/apps/agri-biz'
      preLoaderRoute: typeof AppsAgriBizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apps/animal-clinic': {
      id: '/apps/animal-clinic'
      path: '/apps/animal-clinic'
      fullPath: '/apps/animal-clinic'
      preLoaderRoute: typeof AppsAnimalClinicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apps/education': {
      id: '/apps/education'
      path: '/apps/education'
      fullPath: '/apps/education'
      preLoaderRoute: typeof AppsEducationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apps/plant-clinic': {
      id: '/apps/plant-clinic'
      path: '/apps/plant-clinic'
      fullPath: '/apps/plant-clinic'
      preLoaderRoute: typeof AppsPlantClinicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories/$slug': {
      id: '/categories/$slug'
      path: '/$slug'
      fullPath: '/categories/$slug'
      preLoaderRoute: typeof CategoriesSlugRouteImport
      parentRoute: typeof CategoriesRoute
    }
    '/profile/$id': {
      id: '/profile/$id'
      path: '/profile/$id'
      fullPath: '/profile/$id'
      preLoaderRoute: typeof ProfileIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$id': {
      id: '/projects/$id'
      path: '/$id'
      fullPath: '/projects/$id'
      preLoaderRoute: typeof ProjectsIdRouteImport
      parentRoute: typeof ProjectsRoute
    }
  }
}

interface CategoriesRouteChildren {
  CategoriesSlugRoute: typeof CategoriesSlugRoute
}

const CategoriesRouteChildren: CategoriesRouteChildren = {
  CategoriesSlugRoute: CategoriesSlugRoute,
}

const CategoriesRouteWithChildren = CategoriesRoute._addFileChildren(
  CategoriesRouteChildren,
)

interface ProjectsRouteChildren {
  ProjectsIdRoute: typeof ProjectsIdRoute
}

const ProjectsRouteChildren: ProjectsRouteChildren = {
  ProjectsIdRoute: ProjectsIdRoute,
}

const ProjectsRouteWithChildren = ProjectsRoute._addFileChildren(
  ProjectsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CategoriesRoute: CategoriesRouteWithChildren,
  DashboardRoute: DashboardRoute,
  OnboardingRoute: OnboardingRoute,
  ProjectsRoute: ProjectsRouteWithChildren,
  SearchRoute: SearchRoute,
  AppsAgriBizRoute: AppsAgriBizRoute,
  AppsAnimalClinicRoute: AppsAnimalClinicRoute,
  AppsEducationRoute: AppsEducationRoute,
  AppsPlantClinicRoute: AppsPlantClinicRoute,
  ProfileIdRoute: ProfileIdRoute,
  AdminIndexRoute: AdminIndexRoute,
  AppsIndexRoute: AppsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
